<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("dev");
?><?$APPLICATION->IncludeComponent("bitrix:catalog.section", "brands_list", Array(
	"ACTION_VARIABLE" => "action",	// Название переменной, в которой передается действие
		"ADD_PICT_PROP" => "-",	// Дополнительная картинка основного товара
		"ADD_PROPERTIES_TO_BASKET" => "Y",	// Добавлять в корзину свойства товаров и предложений
		"ADD_SECTIONS_CHAIN" => "N",	// Включать раздел в цепочку навигации
		"ADD_TO_BASKET_ACTION" => "ADD",	// Показывать кнопку добавления в корзину или покупки
		"AJAX_MODE" => "N",	// Включить режим AJAX
		"AJAX_OPTION_ADDITIONAL" => "",	// Дополнительный идентификатор
		"AJAX_OPTION_HISTORY" => "N",	// Включить эмуляцию навигации браузера
		"AJAX_OPTION_JUMP" => "N",	// Включить прокрутку к началу компонента
		"AJAX_OPTION_STYLE" => "Y",	// Включить подгрузку стилей
		"BACKGROUND_IMAGE" => "-",	// Установить фоновую картинку для шаблона из свойства
		"BASKET_URL" => "/personal/basket.php",	// URL, ведущий на страницу с корзиной покупателя
		"BROWSER_TITLE" => "-",	// Установить заголовок окна браузера из свойства
		"CACHE_FILTER" => "N",	// Кешировать при установленном фильтре
		"CACHE_GROUPS" => "Y",	// Учитывать права доступа
		"CACHE_TIME" => "36000000",	// Время кеширования (сек.)
		"CACHE_TYPE" => "A",	// Тип кеширования
		"COMPATIBLE_MODE" => "Y",	// Включить режим совместимости
		"CONVERT_CURRENCY" => "N",	// Показывать цены в одной валюте
		"CUSTOM_FILTER" => "",
		"DETAIL_URL" => "",	// URL, ведущий на страницу с содержимым элемента раздела
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",	// Не подключать js-библиотеки в компоненте
		"DISPLAY_BOTTOM_PAGER" => "Y",	// Выводить под списком
		"DISPLAY_COMPARE" => "N",	// Разрешить сравнение товаров
		"DISPLAY_TOP_PAGER" => "N",	// Выводить над списком
		"ELEMENT_SORT_FIELD" => "sort",	// По какому полю сортируем элементы
		"ELEMENT_SORT_FIELD2" => "id",	// Поле для второй сортировки элементов
		"ELEMENT_SORT_ORDER" => "asc",	// Порядок сортировки элементов
		"ELEMENT_SORT_ORDER2" => "desc",	// Порядок второй сортировки элементов
		"ENLARGE_PRODUCT" => "STRICT",
		"FILTER_NAME" => "arrFilter",	// Имя массива со значениями фильтра для фильтрации элементов
		"HIDE_NOT_AVAILABLE" => "N",	// Недоступные товары
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",	// Недоступные торговые предложения
		"IBLOCK_ID" => "1",	// Инфоблок
		"IBLOCK_TYPE" => "catalog",	// Тип инфоблока
		"INCLUDE_SUBSECTIONS" => "Y",	// Показывать элементы подразделов раздела
		"LABEL_PROP" => "-",	// Свойство меток товара
		"LAZY_LOAD" => "N",
		"LINE_ELEMENT_COUNT" => "3",	// Количество элементов выводимых в одной строке таблицы
		"LOAD_ON_SCROLL" => "N",
		"MESSAGE_404" => "",	// Сообщение для показа (по умолчанию из компонента)
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",	// Текст кнопки "Добавить в корзину"
		"MESS_BTN_BUY" => "Купить",	// Текст кнопки "Купить"
		"MESS_BTN_DETAIL" => "Подробнее",	// Текст кнопки "Подробнее"
		"MESS_BTN_SUBSCRIBE" => "Подписаться",	// Текст кнопки "Уведомить о поступлении"
		"MESS_NOT_AVAILABLE" => "Нет в наличии",	// Сообщение об отсутствии товара
		"META_DESCRIPTION" => "-",	// Установить описание страницы из свойства
		"META_KEYWORDS" => "-",	// Установить ключевые слова страницы из свойства
		"OFFERS_CART_PROPERTIES" => "",	// Свойства предложений, добавляемые в корзину
		"OFFERS_FIELD_CODE" => array(	// Поля предложений
			0 => "",
			1 => "",
		),
		"OFFERS_LIMIT" => "5",	// Максимальное количество предложений для показа (0 - все)
		"OFFERS_PROPERTY_CODE" => array(	// Свойства предложений
			0 => "",
			1 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",	// По какому полю сортируем предложения товара
		"OFFERS_SORT_FIELD2" => "id",	// Поле для второй сортировки предложений товара
		"OFFERS_SORT_ORDER" => "asc",	// Порядок сортировки предложений товара
		"OFFERS_SORT_ORDER2" => "desc",	// Порядок второй сортировки предложений товара
		"PAGER_BASE_LINK_ENABLE" => "N",	// Включить обработку ссылок
		"PAGER_DESC_NUMBERING" => "N",	// Использовать обратную навигацию
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",	// Время кеширования страниц для обратной навигации
		"PAGER_SHOW_ALL" => "N",	// Показывать ссылку "Все"
		"PAGER_SHOW_ALWAYS" => "N",	// Выводить всегда
		"PAGER_TEMPLATE" => ".default",	// Шаблон постраничной навигации
		"PAGER_TITLE" => "Товары",	// Название категорий
		"PAGE_ELEMENT_COUNT" => "52",	// Количество элементов на странице
		"PARTIAL_PRODUCT_PROPERTIES" => "N",	// Разрешить добавлять в корзину товары, у которых заполнены не все характеристики
		"PRICE_CODE" => array(	// Тип цены
			0 => "MAIN_RETAIL",
			1 => "ОПТ РУБ (ОТ 50000 руб)",
			2 => "MAIN4_RETAIL",
			3 => "MAIN1_OPT1",
			4 => "MAIN4_OPT1",
			5 => "MAIN1_OPT2",
			6 => "MAIN4_OPT2",
			7 => "MAIN1_OPT3",
			8 => "MAIN4_OPT3",
			9 => "MAIN2_OPT1",
			10 => "MAIN5_RETAIL",
			11 => "MAIN2_OPT2",
			12 => "MAIN5_OPT1",
			13 => "MAIN2_OPT3",
			14 => "MAIN5_OPT2",
			15 => "MAIN3_OPT1",
			16 => "MAIN5_OPT3",
			17 => "MAIN3_OPT2",
			18 => "MAIN3_OPT3",
			19 => "MAIN1_RETAIL",
			20 => "КРУПНЫЙ ОПТ РУБ",
			21 => "MAIN2_RETAIL",
			22 => "СПЕЦ ЦЕНА РУБ",
			23 => "MAIN3_RETAIL",
		),
		"PRICE_VAT_INCLUDE" => "Y",	// Включать НДС в цену
		"PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons,compare",
		"PRODUCT_DISPLAY_MODE" => "N",	// Схема отображения
		"PRODUCT_ID_VARIABLE" => "id",	// Название переменной, в которой передается код товара для покупки
		"PRODUCT_PROPERTIES" => "",	// Характеристики товара
		"PRODUCT_PROPS_VARIABLE" => "prop",	// Название переменной, в которой передаются характеристики товара
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",	// Название переменной, в которой передается количество товара
		"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"PRODUCT_SUBSCRIPTION" => "Y",	// Разрешить оповещения для отсутствующих товаров
		"PROPERTY_CODE" => array(	// Свойства
			0 => "LOGICTIM_BONUS_BALLS",
			1 => "VES_V_KG",
			2 => "SPOSOB_IZGOTOVLENIYA",
			3 => "STRANA_PROIZVODITEL",
			4 => "TORGOVAYA_MARKA_1",
			5 => "LOGICTIM_BONUS_NO",
			6 => "_1PAKING",
			7 => "KOL_VO_V_UPAKOVKE",
			8 => "MATERIAL",
			9 => "SERIYA_DEL",
			10 => "_REPLIIKI",
			11 => "PRINTSIP_DEYSTVIYA",
			12 => "SKOROST_VYLETA_SHARA",
			13 => "VERSIYA_GIRBOKSA",
			14 => "VERSIYA_GIRBOKSA_1",
			15 => "PAKING_SHARY_REPLIKI_ZAPCHASTI_DLYA_POSTUPLENIYA_3",
			16 => "CML2_ARTICLE",
			17 => "CML2_BASE_UNIT",
			18 => "EMKOST_AKB",
			19 => "PEREVOZCHIK",
			20 => "OFTEN_BUY",
			21 => "CML2_MANUFACTURER",
			22 => "CML2_TRAITS",
			23 => "CML2_TAXES",
			24 => "CML2_ATTRIBUTES",
			25 => "CML2_BAR_CODE",
			26 => "NAPRYAZHENIE",
			27 => "RAZEM_AKB",
			28 => "SOVMESTIMOST",
			29 => "SOVMESTIMOST_1",
			30 => "SOVMESTIMOST_2",
			31 => "TIP_GAZA",
			32 => "MATERIAL_IZGOTOVLENIYA",
			33 => "MOTOR",
			34 => "KOL_VO_V_UPAKOVKE_1",
			35 => "PODSHIPNIKI",
			36 => "SERIYA",
			37 => "VNUTRENNIY_STVOLIK",
			38 => "EMKOST_BALLONA",
			39 => "PROIZVODITEL",
			40 => "VOLTAZH",
			41 => "MAGAZIN",
			42 => "OBEM_MAGAZINA",
			43 => "UVELICHENIE",
			44 => "VES_AVTOMATA_V_KG",
			45 => "TIP_SHARA",
			46 => "DLINA_",
			47 => "TIP_MOTORA",
			48 => "BLOW_BACK",
			49 => "VNUTRENNIY_DIAMETR",
			50 => "EMKOST",
			51 => "A_TACS_FG",
			52 => "DLINA_SHTOKA",
			53 => "SERIYA_",
			54 => "PRINTSIP_DEYSTVIYA_1",
			55 => "TIP_AKB",
			56 => "VSTAVKA_POD_DIOPTRII",
			57 => "REMAINS_MAIN",
			58 => "REMAINS_MAIN3",
			59 => "REMAINS_MAIN1",
			60 => "REMAINS_MAIN4",
			61 => "SHIRINA_MM",
			62 => "VES_KASKI",
			63 => "VYSOTA_MM",
			64 => "GLUBINA_MM",
			65 => "TIP",
			66 => "VES_SHARA",
			67 => "EMKOST_AKB_1",
			68 => "AKTSIYA",
			69 => "NOVINKA_1",
			70 => "SPETSIALNAYA_SKIDKA_",
			71 => "TSVET",
			72 => "RAZMER",
			73 => "TORGOVAYA_MARKA",
			74 => "BUKH_PEREVOZCHIK",
			75 => "",
		),
		"PROPERTY_CODE_MOBILE" => "",
		"RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
		"RCM_TYPE" => "personal",
		"SECTION_CODE" => "",	// Код раздела
		"SECTION_ID" => $_REQUEST["SECTION_ID"],	// ID раздела
		"SECTION_ID_VARIABLE" => "SECTION_ID",	// Название переменной, в которой передается код группы
		"SECTION_URL" => "",	// URL, ведущий на страницу с содержимым раздела
		"SECTION_USER_FIELDS" => array(	// Свойства раздела
			0 => "",
			1 => "",
		),
		"SEF_MODE" => "N",	// Включить поддержку ЧПУ
		"SET_BROWSER_TITLE" => "N",	// Устанавливать заголовок окна браузера
		"SET_LAST_MODIFIED" => "N",	// Устанавливать в заголовках ответа время модификации страницы
		"SET_META_DESCRIPTION" => "N",	// Устанавливать описание страницы
		"SET_META_KEYWORDS" => "N",	// Устанавливать ключевые слова страницы
		"SET_STATUS_404" => "N",	// Устанавливать статус 404
		"SET_TITLE" => "N",	// Устанавливать заголовок страницы
		"SHOW_404" => "N",	// Показ специальной страницы
		"SHOW_ALL_WO_SECTION" => "Y",	// Показывать все элементы, если не указан раздел
		"SHOW_CLOSE_POPUP" => "N",	// Показывать кнопку продолжения покупок во всплывающих окнах
		"SHOW_DISCOUNT_PERCENT" => "N",	// Показывать процент скидки
		"SHOW_FROM_SECTION" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_OLD_PRICE" => "N",	// Показывать старую цену
		"SHOW_PRICE_COUNT" => "1",	// Выводить цены для количества
		"SHOW_SLIDER" => "N",
		"SLIDER_INTERVAL" => "3000",
		"SLIDER_PROGRESS" => "N",
		"TEMPLATE_THEME" => "blue",	// Цветовая тема
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",	// Использовать основной раздел для показа элемента
		"USE_PRICE_COUNT" => "N",	// Использовать вывод цен с диапазонами
		"USE_PRODUCT_QUANTITY" => "Y",	// Разрешить указание количества товара
		"COMPONENT_TEMPLATE" => "aktsii",
		"MESS_BTN_COMPARE" => "Сравнить",	// Текст кнопки "Сравнить"
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>